### ISSUE TITLE
Finding Good Learning Rate For Different Values of Depth, Heads

### ISSUE THREAD

**Issue by afiaka87** [lucidrains/DALLE-pytorch#84]
edit: Most important result I've found is that a **learning rate of 4e-4 to 5e-4 works better than 3e-4 for depth >= 26**. Increase the default when training with higher depth!

I had access to two A100's with 40 GiB of VRAM yesterday so I did a "hyperparameter sweep" with Weights and Biases.

I only chose three parameters to tune: learning rate, depth and heads. 

Wandb ran the first 1200 iterations of a training session 48 times while varying those values. Here are the results:

https://wandb.ai/afiaka87/hp_tuning/reports/DALLE-Pytorch-Sweep-over-Learning-Rate-Depth-and-Heads--Vmlldzo1Mjg4Mjk

![loss-over-time-and-importance](https://user-images.githubusercontent.com/3994972/111044932-0f3e8c80-8411-11eb-88f6-863881ee0c0b.png)
![all_params](https://user-images.githubusercontent.com/3994972/111044700-c63a0880-840f-11eb-8402-0a063211dc75.png)

**Comment by afiaka87** [comment]
Here is the sweep.yml I used. I also had to modfiy train_dalle.py to accept learning rate, depth and heads as arguments. Aside from that, it's pretty much a "one-button click" process. Which is super useful! You can even run the same code in _the same docker container_ on a totally different machine. Allows for much cheaper hyperparameter tuning because it lends itself well to pre-emptible instances and even google colab. 

```yaml
method: random
metric:
  goal: minimize
  name: dalle_loss
parameters:
  depth:
    distribution: int_uniform
    max: 32
    min: 16
  heads:
    distribution: int_uniform
    max: 8
    min: 2
  learning_rate:
    distribution: uniform
    max: 0.0005
    min: 0.0001
program: train_dalle.py
```
